### ISSUE TITLE
calibrate.py crashes when EXIF doesn't have lens model

### ISSUE THREAD

**Issue by 10110111** [lensfun/lensfun#1190]
I'm using a dumb lens without any electronics on a Canon 1100D, and this results in `LensModel` tag not being present. The result is this output of `calibrate.py`:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./calibrate.py", line 162, in call_exiv2
    fieldname, field_value = data.split(None, 1)
ValueError: not enough values to unpack (expected 2, got 1)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./calibrate.py", line 296, in <module>
    for group_exif_data in pool.map(call_exiv2, candidate_groups):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: not enough values to unpack (expected 2, got 1)
```

You can reproduce this result by simply making a shot with a lens disconnected from a Canon EOS DSLR, and putting it into `distortion` directory before running `calibrate.py`.

**Comment by tuxfanx** [comment]
Please read [here](https://wilson.bronger.org/lens_calibration_tutorial/#id9) (section "Exif trouble")
