### ISSUE TITLE
ASAN error calling lensfun 0.3.95-2 from darktable (master)

### ISSUE THREAD

**Issue by codingdave** [lensfun/lensfun#1213]
Running darktable master (darktable 3.1.0+2475~g08eba104b) on manjaro linux I get this ASAN report on startup (every time).

If you need any more information, I am happy to provide that. @bronger you can also reach me in IRC #darktable with the nick saulus.

Running latest lensfun master does not compile.

Cheers
Dave

=================================================================
==180533==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000c87113 at pc 0x7fefb6fb91ca bp 0x7ffdd13c7e20 sp 0x7ffdd13c75c8
WRITE of size 4 at 0x602000c87113 thread T0
    #0 0x7fefb6fb91c9 in __interceptor_memcpy /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806
    #1 0x7fef992a7f24 in lfMount::AddCompat(char const*) (/usr/lib/liblensfun.so.2+0x35f24)
    #2 0x7fef99289065  (/usr/lib/liblensfun.so.2+0x17065)
    #3 0x7fefb5ef1369 in g_markup_parse_context_parse (/usr/lib/libglib-2.0.so.0+0x55369)
    #4 0x7fef9928b102 in lfDatabase::Load(char const*, char const*, unsigned long) (/usr/lib/liblensfun.so.2+0x19102)
    #5 0x7fef9928cdb5 in lfDatabase::Load(char const*) (/usr/lib/liblensfun.so.2+0x1adb5)
    #6 0x7fef9928cdef in lfDatabase::Load(char const*) (/usr/lib/liblensfun.so.2+0x1adef)
    #7 0x7fef9928cc0c in lfDatabase::Load() (/usr/lib/liblensfun.so.2+0x1ac0c)
    #8 0x7fef993230b3 in init_global /home/david/workspace/darktable.git/src/iop/lens.cc:1256
    #9 0x7fefb68f3ff2 in dt_iop_load_module_so /home/david/workspace/darktable.git/src/develop/imageop.c:436
    #10 0x7fefb680b6b0 in dt_module_load_modules /home/david/workspace/darktable.git/src/common/module.c:49
    #11 0x7fefb68f5ee5 in dt_iop_load_modules_so /home/david/workspace/darktable.git/src/develop/imageop.c:1544
    #12 0x7fefb66f4a76 in dt_init /home/david/workspace/darktable.git/src/common/darktable.c:984
    #13 0x55919510a0b5 in main /home/david/workspace/darktable.git/src/main.c:92
    #14 0x7fefb639e001 in __libc_start_main (/usr/lib/libc.so.6+0x27001)
    #15 0x55919510a13d in _start (/home/david/unstable/darktable_master/bin/darktable+0x113d)

0x602000c87113 is located 0 bytes to the right of 3-byte region [0x602000c87110,0x602000c87113)
allocated by thread T0 here:
    #0 0x7fefb7031459 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7fef992a7f0f in lfMount::AddCompat(char const*) (/usr/lib/liblensfun.so.2+0x35f0f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /build/gcc/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x0c0480188dd0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480188de0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c0480188df0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 02 fa
  0x0c0480188e00: fa fa 03 fa fa fa fd fa fa fa fd fa fa fa 00 fa
  0x0c0480188e10: fa fa 06 fa fa fa fd fa fa fa 00 04 fa fa 00 01
=>0x0c0480188e20: fa fa[03]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480188e30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480188e40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480188e50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480188e60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480188e70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==180533==ABORTING

**Comment by codingdave** [comment]
seems to have fixed with de954c952929316ea2ad0f6f1e336d9d8164ace0 already
