### ISSUE TITLE
wilson.bronger.org seems to be down, which causes error

### ISSUE THREAD

**Issue by ilyapopov** [lensfun/lensfun#1798]
While running `lensfun-update-data`, I see the following error:

```
Reading http://lensfun.sourceforge.net/db/versions.json …
Reading http://wilson.bronger.org/lensfun-db/versions.json …
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/lensfun-update-data", line 134, in <module>
    read_location("http://wilson.bronger.org/lensfun-db/")
  File "/usr/bin/lensfun-update-data", line 116, in read_location
    response = urllib.request.urlopen(base_url + "versions.json")
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>
```
System: Ubuntu 22.04
lensfun version: 0.3.2-6 from Ubuntu repos
Python 3.10.4

**Comment by bronger** [comment]
Because it is a private computer without redundancy, it does not have 24/7 availability, however, its outages are only for a couple of minutes once a week or so.

However, I designed `lensfun-update-data` itself redundant. It should just move to another database source. In particular, the above exception is actually caught in https://github.com/lensfun/lensfun/blob/master/apps/lensfun-update-data#L119 and dealt with gracefully.

**Comment by ilyapopov** [comment]
Yes, indeed, it should have been handled. However, you can see that the line "Error: URL could not be opened, skipping:" was not printed, indicating it was not handled. Upon examination, I found that the version I have on my system, does not handle `urllib.error.URLError` yet. Current master version is fine. 

This issue can therefore be closed.
