### ISSUE TITLE
setuptools does not like me

### ISSUE THREAD

**Issue by rubyFeedback** [lensfun/lensfun#2351]
make
[  6%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/camera.cpp.o
[ 12%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/database.cpp.o
[ 18%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/lens.cpp.o
[ 25%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mount.cpp.o
[ 31%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/cpuid.cpp.o
[ 37%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse.cpp.o
[ 43%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color-sse2.cpp.o
[ 50%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-color.cpp.o
[ 56%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord-sse.cpp.o
[ 62%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-coord.cpp.o
[ 68%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-pc.cpp.o
[ 75%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/mod-subpix.cpp.o
[ 81%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/modifier.cpp.o
[ 87%] Building CXX object libs/lensfun/CMakeFiles/lensfun.dir/auxfun.cpp.o
[ 93%] Linking CXX shared library liblensfun.so
[ 93%] Built target lensfun
[100%] Generating build/timestamp
Traceback (most recent call last):
  File "/depot/jjjj/lensfun/BUILD_DIRECTORY/apps/setup.py", line 6, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
make[2]: *** [apps/CMakeFiles/python-package.dir/build.make:74: apps/build/timestamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:157: apps/CMakeFiles/python-package.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
make install
[ 93%] Built target lensfun
[100%] Generating build/timestamp
Traceback (most recent call last):
  File "/depot/jjjj/lensfun/BUILD_DIRECTORY/apps/setup.py", line 6, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
make[2]: *** [apps/CMakeFiles/python-package.dir/build.make:74: apps/build/timestamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:157: apps/CMakeFiles/python-package.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

------------

So, this is python related, but I think lensfun works without python. I just compiled version 0.3.x
without any issue. Python kind of works for me too, though not sure why setuptools fails.

Either way, can this be optional? I don't want to run into an install-error because of python, when
the rest of lensfun should work fine, IMO. It is also weird that it has finished, at 100% but then fails
due to ... setuptools. (Which I think is python's fault, but still - it should not propagate to the user.
My python installation works fine by the way, I am on 3.11.9; will probably upgrade soon, as I keep on having issues. Python drove itself into a mess in the last 2 years in regards to add-ons really.)

**Comment by jonas-ott** [comment]
Running CMake with `-DINSTALL_PYTHON_MODULE=OFF` should work. 
Otherwise related to #2237? Could you test #2256?
